### ISSUE TITLE
Optimization removes extern definitions

### ISSUE THREAD

**Issue by samvher** [sdiehl/kaleidoscope#27]
I implemented everything up to Chapter 4 and have a small issue. For some reason, if I use extern in the REPL, the optimization pass removes the function definition straight away.

```
ready> extern sin(x);
; ModuleID = 'my cool jit'
```

if I uncomment the line with `runPassManager pm m` in JIT.hs, it works as it should:

```
ready> extern sin(x);
; ModuleID = 'my cool jit'

declare double @sin(double)
```

I've been looking if I can find a way to omit the optimization pass that removes the declaration but no luck so far.

I'm running llvm-3.5, maybe something changed w.r.t. default optimization passes? I tried setting the optimization to levels 2/1 instead of 3 but the problem persists.

**Comment by yigitozkavci** [comment]
Yes, I had this issue as well. And solved it by disabling `optLevel` pass, which I noticed in commented-out portion here: https://github.com/sdiehl/kaleidoscope/blob/master/src/chapter4/JIT.hs#L44

Don't know why, but I could not get it working via `optLevel = 3` optimization as well. I don't have the same problem with other optimization passes by the way, just with optLevel.

Maybe we should have some explanation on the subject in tutorial, since it might be hard to notice that this may be caused by having the optLevel 3 @sdiehl
